import { Images } from "./Images";
import {
  faTwitter,
  faInstagram,
  faFacebook,
} from "@fortawesome/free-brands-svg-icons";

export const Data = {
  team: [
    {
      img: Images.teamMembers.team1,
      name: "Username",
      role: "Profession",
      socials: [faFacebook, faInstagram, faTwitter],
    },
    {
      img: Images.teamMembers.team2,
      name: "Username",
      role: "Profession",
      socials: [faFacebook, faInstagram, faTwitter],
    },
    {
      img: Images.teamMembers.team3,
      name: "Username",
      role: "Profession",
      socials: [faFacebook, faInstagram, faTwitter],
    },
    {
      img: Images.teamMembers.team4,
      name: "Username",
      role: "Profession",
      socials: [faFacebook, faInstagram, faTwitter],
    },
    {
      img: Images.teamMembers.team5,
      name: "Username",
      role: "Profession",
      socials: [faFacebook, faInstagram, faTwitter],
    },
    {
      img: Images.teamMembers.team6,
      name: "Username",
      role: "Profession",
      socials: [faFacebook, faInstagram, faTwitter],
    },
    {
      img: Images.teamMembers.team7,
      name: "Username",
      role: "Profession",
      socials: [faFacebook, faInstagram, faTwitter],
    },
    {
      img: Images.teamMembers.team8,
      name: "Username",
      role: "Profession",
      socials: [faFacebook, faInstagram, faTwitter],
    },
    {
      img: Images.teamMembers.team9,
      name: "Username",
      role: "Profession",
      socials: [faFacebook, faInstagram, faTwitter],
    },
  ],
  bestSellers: [
    {
      img: Images.homeProductCard.productCard1,
      collection: "Graphic Design",
      product: "English Department",
      price: "$16.48",
      discountedPrice: "$6.48",
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      key: 1,
    },
    {
      img: Images.homeProductCard.productCard2,
      collection: "Graphic Design",
      product: "English Department",
      price: "$16.48",
      discountedPrice: "$6.48",
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      key: 2,
    },
    {
      img: Images.homeProductCard.productCard3,
      collection: "Graphic Design",
      product: "English Department",
      price: "$16.48",
      discountedPrice: "$6.48",
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      key: 3,
    },
    {
      img: Images.homeProductCard.productCard4,
      collection: "Graphic Design",
      product: "English Department",
      price: "$16.48",
      discountedPrice: "$6.48",
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      key: 4,
    },
    {
      img: Images.homeProductCard.productCard5,
      collection: "Graphic Design",
      product: "English Department",
      price: "$16.48",
      discountedPrice: "$6.48",
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      key: 5,
    },
    {
      img: Images.homeProductCard.productCard6,
      collection: "Graphic Design",
      product: "English Department",
      price: "$16.48",
      discountedPrice: "$6.48",
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      key: 6,
    },
    {
      img: Images.homeProductCard.productCard7,
      collection: "Graphic Design",
      product: "English Department",
      price: "$16.48",
      discountedPrice: "$6.48",
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      key: 7,
    },
    {
      img: Images.homeProductCard.productCard8,
      collection: "Graphic Design",
      product: "English Department",
      price: "$16.48",
      discountedPrice: "$6.48",
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      key: 8,
    },
  ],

  featuredPosts: {
    featured1: {
      img: Images.featuredPosts.featured1,
      categories: ["Google", "Trending", "New"],
      header: "Loudest à la Madison #1 (L'integral)",
      description:
        "We focus on ergonomics and meeting you where you work. It's only a keystroke away.",
      date: "22 April 2022",
      comments: "10 comments",
    },
    featured2: {
      img: Images.featuredPosts.featured2,
      categories: ["Google", "Trending", "New"],
      header: "Loudest à la Madison #1 (L'integral)",
      description:
        "We focus on ergonomics and meeting you where you work. It's only a keystroke away.",
      date: "22 April 2022",
      comments: "10 comments",
    },
    featured3: {
      img: Images.featuredPosts.featured3,
      categories: ["Google", "Trending", "New"],
      header: "Loudest à la Madison #1 (L'integral)",
      description:
        "We focus on ergonomics and meeting you where you work. It's only a keystroke away.",
      date: "22 April 2022",
      comments: "10 comments",
    },
  },
  categories: [
    {
      category: "CLOTHS",
      number: "14 items",
      img: Images.categories.category1,
    },
    {
      category: "JEANS",
      number: "5 items",
      img: Images.categories.category2,
    },
    {
      category: "COATS",
      number: "12 items",
      img: Images.categories.category3,
    },
    {
      category: "SWEATSHIRTS",
      number: "16 items",
      img: Images.categories.category4,
    },
    {
      category: "T-SHIRTS",
      number: "24 items",
      img: Images.categories.category5,
    },
  ],
  productList: [
    {
      key: 1,
      id: 1,
      name: "Graphic Design",
      category: "English Department",
      price: 16.48,
      discountedPrice: 6.48,
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      img: Images.productList.productList1,
    },
    {
      key: 2,
      id: 2,
      name: "Graphic Design",
      category: "English Department",
      price: 16.48,
      discountedPrice: 6.48,
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      img: Images.productList.productList2,
    },
    {
      key: 3,
      id: 3,
      name: "Graphic Design",
      category: "English Department",
      price: 16.48,
      discountedPrice: 6.48,
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      img: Images.productList.productList3,
    },
    {
      key: 4,
      id: 4,
      name: "Graphic Design",
      category: "English Department",
      price: 16.48,
      discountedPrice: 6.48,
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      img: Images.productList.productList4,
    },
    {
      id: 5,
      key: 5,
      name: "Graphic Design",
      category: "English Department",
      price: 16.48,
      discountedPrice: 6.48,
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      img: Images.productList.productList5,
    },
    {
      key: 6,
      id: 6,
      name: "Graphic Design",
      category: "English Department",
      price: 16.48,
      discountedPrice: 6.48,
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      img: Images.productList.productList6,
    },
    {
      key: 7,
      id: 7,
      name: "Graphic Design",
      category: "English Department",
      price: 16.48,
      discountedPrice: 6.48,
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      img: Images.productList.productList7,
    },
    {
      key: 8,
      id: 8,
      name: "Graphic Design",
      category: "English Department",
      price: 16.48,
      discountedPrice: 6.48,
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      img: Images.productList.productList8,
    },
    {
      key: 9,
      id: 9,
      name: "Graphic Design",
      category: "English Department",
      price: 16.48,
      discountedPrice: 6.48,
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      img: Images.productList.productList9,
    },
    {
      key: 10,
      id: 10,
      name: "Graphic Design",
      category: "English Department",
      price: 16.48,
      discountedPrice: 6.48,
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      img: Images.productList.productList10,
    },
    {
      key: 11,
      id: 11,
      name: "Graphic Design",
      category: "English Department",
      price: 16.48,
      discountedPrice: 6.48,
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      img: Images.productList.productList11,
    },
    {
      key: 12,
      id: 12,
      name: "Graphic Design",
      category: "English Department",
      price: 16.48,
      discountedPrice: 6.48,
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      img: Images.productList.productList12,
    },
  ],
};
